### ISSUE TITLE
Detect Testnets (Ropsten, Kovan, ...) and Mainnet

### ISSUE THREAD

**Issue by shayanb** [auctionify/auctionify#23]
Detect the network. The network could be shown on the page, maybe using the similar `Logged in as 0xABC` on top right corner? 

Fixes for Mainnet: 
- [x] Infura web socket url: from `main.infura.io/ws/` to `mainnet.infura.io/ws/`

**Comment by amir-s** [comment]
fixed by https://github.com/auctionify/auctionify/commit/03b3d2b28c2905be1fac4e3068353b8d77332329
